server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    password: "postgres"
    url: "jdbc:postgresql://localhost:5432/graduation_project"
    username: "newuser"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true
    show_sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: true
    change-log: "classpath:db/changelog/db.changelog-master.xml"
    contexts: "sql,data"

ecommerce:
  app:
    jwtCookieName: graduationproject
    jwtSecret: "jwt_secret"
    jwtExpirationMs: 86400000