server:
  port: 80
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    password: "postgres"
    url: "jdbc:postgresql://localhost:5432/graduation_project"
    username: "postgres"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true
    show_sql: true

ecommerce:
  app:
    jwtCookieName: graduationproject
    jwtSecret: "jwt_secret"
    jwtExpirationMs: 86400000